### ISSUE TITLE
Improve JSON body documentation

### ISSUE THREAD

**Issue by jntakpe** [Ninja-Squad/spring-rest-docs-kotlin#12]
@jnizet I have created a project focused on providing a way to fluently document request and response bodies with a JSON like syntax.
Have a look at it and maybe you will find reusable bits.

**Comment by jnizet** [comment]
Thanks @jntakpe 

I've had a quick look (I guess you're talking about https://github.com/jntakpe/spring-restdocs-dsl)

I've never actually thought about using reflection (`User::firstName.name`) to get the name of an attribute. That's a neat idea. I get the advantages (automatic refactoring, code completion, no typo), but there are also disadvantages:

- the naming strategy of the JSON serializer must use the actual name of the properties
- the code is more verbose and, IMHO, less readable than with strings
- it only works if you're actually serializing objects, and not maps for example

And unless you use relaxed fields, Spring rest docs will fail if you have a typo in the JSON paths.

But having a hierarchical structure is nice, and in its current state, my DSL allows that:

```
    requestFields {
        add("firstName", "the first name of the user")
        withPrefix("address.") {
            add("street", "the street of the address of the user")
            // ...
        }
    }
```

So it's maybe not as elegant as what you have, but it's lighter, works whatever you use (JSON, XML, with whatever serialization strategy) and, IMHO, is very readable.

You can use reflection with that too i you want, although it hurts readability IMHO.

```
    requestFields {
        add(User::firstName.name, "the first name of the user")
        withPrefix("${User.address.name}.") {
            add(Address::street.name, "the street of the address of the user")
            // ...
        }
    }
```

I see that you're spedifying the type of each field in your example. May I ask why? I never do that, and Spring-REST-Docs automatically infers the type from the actual JSON.

**Comment by jntakpe** [comment]
We are specifying type because we wanted to be explicit about it but maybe that's not a good idea
